# Generated by Django 4.1.1 on 2022-09-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=270)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['storage_date']},
        ),
        migrations.RemoveField(
            model_name='brand',
            name='id',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage_date',
            field=models.DateField(auto_now=True),
        ),
    ]
