# Generated by Django 4.1.1 on 2022-09-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_alter_medicine_options_remove_brand_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={},
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='price',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='storage_date',
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='med_brand_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.brand'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='med_category_name',
            field=models.ManyToManyField(null=True, to='inventory.category'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('inventory_price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('promotion_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('promotion_is_active', models.BooleanField(default=False)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to=None)),
                ('alternative_text', models.CharField(max_length=100)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
    ]
